apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- store1.yml
- store2.yml
- store3.yml
- store4.yml

images:
- name: localhost:producer
  newName: <your-repository-name>:producer
