apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- dr.yml
- frontend.yml
- service.yml
- vs.yml

images:
- name: localhost/frontend
  newName: <your-repository-name>/frontend
