apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: waiter
    version: v2
  name: waiter2
  namespace: kafka
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: waiter
      version: v2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate 
  template:
    metadata:
      labels:
        sidecar.istio.io/inject: "true"
        app: waiter
        version: v2
    spec:
      containers:
      - env:
        - name: JAEGER_ALL_IN_ONE_INMEMORY_COLLECTOR_PORT_14268_TCP_ADDR
          value: jaeger-collector.istio-system.svc
        - name: JAEGER_ALL_IN_ONE_INMEMORY_COLLECTOR_PORT_14268_TCP_PORT
          value: "14268"
        - name: KAFKA_BOOTSTRAP
          value: pizza-kafka-bootstrap:9092
        - name: JOB
          value: "store[234].drinks"
        - name: SPEED
          value: "4"
        image: localhost/consumer:latest
        imagePullPolicy: Always
        name: waiters
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 3
