apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: grafana-traefik
  namespace: istio-system
spec:
  rules:
  - host: grafana-istio.apps.example.com
    http:
      paths:
      - backend:
          service:
            name: grafana
            port:
              number: 3000
        path: /
        pathType: Prefix
status:
  loadBalancer: {}
